import type { MetadataRoute } from "next";

// A web app manifest can only carry literal colors, so the two below are the
// one sanctioned repeat of the locked palette: background_color mirrors --bg
// and theme_color mirrors --accent (light values, app/globals.css). Keep them
// in sync if the palette ever changes.
const BACKGROUND_COLOR = "#EDF3F9";
const THEME_COLOR = "#3D5A80";

// Served at /manifest.webmanifest. Icons are generated by scripts/make-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "WaterTech Bilimlar Bazasi",
    short_name: "WaterTech KB",
    start_url: "/",
    display: "standalone",
    background_color: BACKGROUND_COLOR,
    theme_color: THEME_COLOR,
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    ],
  };
}
